Move feature flags to header to allow better dead code elimination
Placing the feature flag checks directly in the header using inline
functions allows the compiler to eliminate dead code much better.
For example, at the moment NAND and secure boot code (crypto etc)
is included in the binary even though it will never be invoked.

This must be done carefully though: Sometimes the feature flags are
dynamically detected at runtime for some of the supported platforms.
Add some carefully chosen checks to allow inlining the most important
feature flags.

For a minimal build for the "msm8953" platform (with secure boot
disabled), this commit reduces the binary size by about 50%, from
471 KiB to 253 KiB. It also fixes a linker error on msm8996 with
secure boot disabled (undefined reference to `rpmb_init') because
calls to the missing function are eliminated at compile time.