target: msm8996: init: Always include smbchg headers
Otherwise, disabling ENABLE_WBC for msm8996 causes:

target/msm8996/init.c: In function 'target_cont_splash_screen':
compiling platform/msm_shared/debug.c
target/msm8996/init.c:458:33: warning: implicit declaration of function 'pm_appsbl_charging_in_progress' [-Wimplicit-function-declaration]
  458 |         if(!splash_override && !pm_appsbl_charging_in_progress()) {
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compiling platform/msm_shared/smem.c
target/msm8996/init.c: In function 'target_pause_for_battery_charge':
target/msm8996/init.c:649:9: warning: implicit declaration of function 'pm_smbchg_get_charger_path' [-Wimplicit-function-declaration]
  649 |         pm_smbchg_get_charger_path(1, &charger_path);