LK: Fix undefined reference when DEBUG_LEVEL is two
When Debug level is defined as more than 1 compilation fails with
undefined reference to current_time_hires. Implement current_time_hires
to fix this issue.

Change-Id: I9636928f501ac1bd75cdf424ac50c2fab844b3bc