Revert "project: msm8953: Enable secapploader and rpmb support"
This reverts commit 463073c3759dcacffe1acef3314ec46f17d62d17.

The secapp/rpmb stuff is only enabled during verified boot so it does
not make sense to compile it always. It looks like this was only done
to avoid linker errors because the compiler was unable to eliminate
the unused code:

target/msm8953/init.o: In function `target_uninit':
target/msm8953/init.c:532: undefined reference to `is_sec_app_loaded'
target/msm8953/init.c:541: undefined reference to `rpmb_uninit'
target/msm8953/init.c:534: undefined reference to `send_milestone_call_to_tz'
target/msm8953/init.o: In function `target_init':
target/msm8953/init.c:398: undefined reference to `rpmb_init'
target/msm8953/init.c:407: undefined reference to `load_sec_app'

With the better dead code elimination thanks to defining some functions
inline in the header this is no longer necessary, msm8953 compiles just
fine without these changes.